[package]
authors = ["realityone <realityone@me.com>"]
name = "pppd-netkeeper"
version = "0.1.1"

[dependencies]
libc = "0.2.43"

[dependencies.libnetkeeper]
features = ["netkeeper"]
git = "https://github.com/realityone/libnetkeeper.git"
tag = "0.2.0"

[lib]
crate-type = ["dylib"]
